### ISSUE TITLE
Project Page Component

### ISSUE THREAD

**Issue by MD-Mohammed** [MD-Mohammed/Gulf-Erection-Company#15]

**Comment by Shejeer-Aboobacker** [comment]
Completed development for both mobile and desktop version @MD-Mohammed

**Comment by Shejeer-Aboobacker** [comment]
Completed development for both mobile and desktop version @MD-Mohammed

**Comment by Shejeer-Aboobacker** [comment]
Completed development for both mobile and desktop version @MD-Mohammed

**Comment by Shejeer-Aboobacker** [comment]
Completed development for both mobile and desktop version @MD-Mohammed
