### ISSUE TITLE
Navigation Bar Component

### ISSUE THREAD

**Issue by MD-Mohammed** [MD-Mohammed/Gulf-Erection-Company#3]
Create Responsive Component for : 

- [x] Desktop
- [x] Mobile

**Comment by Shejeer-Aboobacker** [comment]
Navigation page is loading slow and crashing the browser. We should change the SVG to PNG 


![Image](https://user-images.githubusercontent.com/102415951/181202649-20343254-4fb1-4f57-9fcf-08107a2c2e0f.png)

**Comment by Shejeer-Aboobacker** [comment]
Bug- Mobile component didn't load when I reduced the screensize manually and also in emulator.


![Image](https://user-images.githubusercontent.com/102415951/181203722-5d5cbe0e-dfa6-4401-aa6c-57f926ba6f35.png)
