### ISSUE TITLE
About us page component

### ISSUE THREAD

**Issue by MD-Mohammed** [MD-Mohammed/Gulf-Erection-Company#9]

**Comment by Shejeer-Aboobacker** [comment]
Desktop page completed
Mobile version is pending

**Comment by MD-Mohammed** [comment]
I have made some alignment fixes and merged them directly to the branch.  From next time onwards, we will make sure that we branch out from the branch in review and raise a Pull Request to merge it back so that we can go through it and approve it before merging directly.

**Comment by MD-Mohammed** [comment]
The desktop component is ready for merge for now.
